### PR TITLE
Rnaseq tour

### PR DESCRIPTION
**Pull request by jfallmann**
Tour protoype is assembled, problem is that there is sometimes a lot of text needed,
and it hurts dividing this into dozens of textboxes, I saw #https://github.com/galaxyproject/galaxy-tours/issues/4 that there's already an issue regarding the width of this windows, is there any workaround available? Otherwise the tour is as close to the workshop as possible, needs some love still, but this is doable until 31st

### CODE REVIEW

**Comment by jfallmann** [comment]
@bgruening btw. there is another issue, for the upload of zenodo files by url I'd like to use an action that allows me to insert text into the upload-box#upload-text-info div, similar to the postclick action for file upload from disk, but I couldn't find out how to do this, any idea?

**Comment by bgruening** [comment]
@jfallmann does this help you? https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/tours/core.galaxy_ui.yaml#L46

**Comment by bgruening** [comment]
For the above issue, I don't have a good answer :(
All is based on http://bootstraptour.com/api/ so this can be used as well, but I guess this is a bigger issue.

**Comment by bgruening** [comment]
I added the tour to the container.

**Comment by jfallmann** [comment]
@bgruening Yes, https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/tours/core.galaxy_ui.yaml#L46 seems to be axactly what's needed, I'll fix some stuff for the two tours later and integrate this as well, for the other issue I think we just skip this for now and maybe come back to that in January, or maybe it's easier to just split the text in more windows until there's a solid solution

**Comment by bgruening** [comment]
Splitting into multiple boxes sounds like a good idea. The text is great and we should not loose it until this is fixed.
Thanks a lot!
I will be busy today, but will write tomorrow the one page abstract.

**Pull request merged**
