### PR TITLE
added TOC and buttons to navigate the howtos

### PR DESCRIPTION
**Pull request by bagnacan**
I divided the howtos into sections, adding:
- a table of contents;
- buttons to go "back to top";
- small troubleshooting section.

I updated the screenshots' file names to be more informative about the section they belong to, and slightly updated thw wording of each sentence.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @bagnacan! The headers do not seem to render correctly. You can check this on github using the "show" button in your PR.

**Comment by bagnacan** [comment]
Thanks, Bjoern.
Sorry I didn't notice it before: the whole render looked good using "grip" (https://github.com/joeyespo/grip). I'll look into it

**Comment by bagnacan** [comment]
Headers now render correctly

**Comment by bgruening** [comment]
This looks nice! Thanks.
I think we need to make more clear on the main readme that all what is needed is just Docker - AND you can get Docker in various ... Kitematik is one which we recommend for WIn/OSX users. Somehow the reviewer was confused by Docker and Kitematik.

**Comment by bagnacan** [comment]
I'll take care of it then, thanks for the heads-up.
I'll add a TOC as well if you're fine with this: the whole readme has become pretty long.

**Comment by bgruening** [comment]
Yes, please I love the TOC and the "got to the top" stuff. I would like to have this as well for the docker-stable project. Looks so much better than my stuff :)

**Comment by bgruening** [comment]
Please also check: http://bgruening.github.io/galaxy-rna-workbench/
This should not break and look also nice.

**Pull request merged**
