### PR TITLE
Update ncRNA workflow

### PR DESCRIPTION
**Pull request by s-will**

### CODE REVIEW

**Comment by s-will** [comment]
Hi @bgruening, I updated/checked the RNAz parameters. But I could not figure out, what you wrote about updating the Infernal version; it seems to me this is already ok, isn't it?

**Comment by bgruening** [comment]
I fixed infernal, yes, just added the old version as well. So we have now two version.

**Comment by bgruening** [comment]
So if you want to can add the new infernal version to the workflow as well. Just remove the old and add the new one from the left hand side of the menu.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
