### PR TITLE
Update 17.05

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@bebatut @yhoogstrate @dyusuf @eggzilla @pavanvidem @jfallmann I would like to merge this at some point, but the manuscript will be published every day. I would appreciate any testing before merge. Travis tests a lot but probably not everything. So if you could run a few tours, workflows etc. this would be great.

There will be a quay.io image https://quay.io/repository/bgruening/galaxy-rna-workbench?tab=builds with the tag `update_17.05` soon.

**Comment by eggzilla** [comment]
I will test in the next days, just have to wrap up two other things. Apologies for the delay.

**Comment by dyusuf** [comment]
hi all, I had a quick test on the new version, `quay.io/bgruening/galaxy-rna-workbench:update_17.05`, it worked fine with tour and workflow. 

well, I just noticed the docker container can not fetch online date such as the following error:
```
Unable to fetch https://raw.githubusercontent.com/bgruening/galaxytools/master/tools/rna_tools/paralyzer/test-data/input.fa
<urlopen error [Errno -2] Name or service not known>
```

This is not the error specific to `update_17.05` since I checked the older version and got the same error as well. Probably this is more related to the docker setting. If so, we may need to specify the related instructions in README.

**Comment by bgruening** [comment]
@dyusuf thanks for testing. How did you tried to get this data? Via the upload tool?

**Comment by dyusuf** [comment]
yes, Upload File -> Paste/Fetch Data.

it worked fine with local file

**Comment by bgruening** [comment]
Thanks will look into it tm!

**Comment by bgruening** [comment]
Mh, works for me.

**Comment by dyusuf** [comment]
ok, then it is related to the local docker setting as I suspected.

so then regarding update_17.05, I don't discover any issue with tour and workflow. both ran well.

**Comment by eggzilla** [comment]
Tested the model construction workflow and the introduction tour, everything seems to work as expected. I would recommend to merge :-)

**Comment by jfallmann** [comment]
@bgruening I have problems with the introduction tour, the automatic file upload of the constraint fasta does not work for me, seems the link is broken?

**Comment by eggzilla** [comment]
Isnt there a link to the repo in the popup, where you can download the constraint file?

**Comment by jfallmann** [comment]
Yes, but this is intended to be done only for the unconstraint file at the beginning, the constraint one should be downloaded automatically when the user clicks next, but nothing happens, no error, just nothing. Rest works fine for me.

**Comment by bgruening** [comment]
@jfallmann which file do you mean, this one? https://raw.githubusercontent.com/jfallmann/test-data/master/viennarna-galaxy-tour/Homo_sapiens_CXCL2_sequence.fa

**Comment by jfallmann** [comment]
@bgruening No, the Homo_sapiens_CXCL2_constraints.fa, clicking next in the tour should trigger a copy-and-paste of the url into the galaxy data upload window and start the upload, but for me nothing happens

**Comment by bgruening** [comment]
Ok, let's see how it goes!

**Comment by bgruening** [comment]
Thanks for testing!

**Comment by bgruening** [comment]
Hi!

17.05 is tagged and released! It can be advertised! `quay.io/bgruening/galaxy-rna-workbench:17.05`

**Pull request merged**
