### PR TITLE
Galaxy VRNA tours

### PR DESCRIPTION
**Pull request by jfallmann**
First running prototype

### CODE REVIEW

**Comment by jfallmann** [comment]
@s-will @bgruening Tour runs, glad for input

**Comment by jfallmann** [comment]
@bgruening Travis errors with 
Error processing tar file(exit status 1): mkdir /tool_deps/_conda/pkgs/scikit-learn-0.18.1-np111py27_0/lib/python2.7/site-packages/sklearn/metrics: no space left on device
restarted build

**Comment by bgruening** [comment]
The error is unrelated and we have a serious testing problem here as travis has limited disc space as it seems :(

**Comment by jfallmann** [comment]
@bgruening Ok, that's bad, maybe there's a way to tell travis that more space is needed for a test, like the travis wait option during conda builds? Maybe we can set up the travis testing container in the "cloud" for local tests?

**Comment by bgruening** [comment]
please see here: https://github.com/bgruening/galaxy-rna-workbench/pull/18

**Pull request merged**
