### PR TITLE
Aresite

### PR DESCRIPTION
**Pull request by jfallmann**

### CODE REVIEW

**Comment by jfallmann** [comment]
@bgruening Running out of travis time again, any idea what we can do?

**Comment by bgruening** [comment]
We need to kindly ask travis to extend our build time.
@jfallmann do you mind putting this tool under rnateam?

**Comment by jfallmann** [comment]
@bgruening, I don't mind, will do, should I ask Travis or do you have a red line already ;)

**Comment by bgruening** [comment]
I ask kindly, next time its your turn ;)

**Comment by bgruening** [comment]
So we have more build time by default - and voila it turns green.

**Comment by jfallmann** [comment]
Very cool, guess that helps a lot! Thx for your effort!

**Pull request merged**
