### PR TITLE
add workflow to analyse set of RNAs and sequence database

### PR DESCRIPTION
**Pull request by s-will**
the workflow uses locarna, RNAz, RNAcode, cmbuild and cmsearch

### CODE REVIEW

**Comment by s-will** [comment]
Hi @bgruening, sorry for the silence, here is at least one workflow. I see, whether I can do more:)

PS: I noticed a bug when running RNAz from a docker rna-workbench with a small multiple alignment as input (this seems to be caused by Galaxy's python code; can you reproduce this?):

Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 909, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/galaxy-central/lib/galaxy/tools/evaluation.py", line 445, in build
    raise e
ValueError: invalid literal for int() with base 10: '-1.0'

invalid literal for int() with base 10: '-1.0'

**Comment by bgruening** [comment]
Thanks. Do you have the example input file to reproduce this error?

**Comment by s-will** [comment]
RNAz failed with this input aln (github forced me to append the txt) and default parameters.
Changing the cutoff didn't help.

[result.aln.txt](https://github.com/bgruening/galaxy-rna-workbench/files/807521/result.aln.txt)

**Comment by s-will** [comment]
To be sure, I just checked that my locally installed RNAz runs on the same input. (RNAz version 2.1)

**Comment by s-will** [comment]
Hi @bgruening, do you understand what Travis is doing here? I cannot view the Travis logs, so that I cannot find out what's going wrong.
PS:Any ideas about the RNAz problem yet?

**Comment by bgruening** [comment]
Travis has some problems since yesterday, more or less all AWS services do have problems. The S3 was gone. Conda, Docker had the same problems :(
RNAz works here, I guess we fixed it and need to rebuild the image.

**Comment by bgruening** [comment]
Mh, something is wrong with this workflow. It crashes during import. I need some more time for this.

**Comment by bgruening** [comment]
Ok, thats the error. Working on it.
```
Error - <type 'exceptions.KeyError'>: 'max_diff_mode'
URL: http://localhost:8080/workflow/import_workflow
File 'lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/galaxy_venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/galaxy_venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 134 in __call__
  return self.handle_request( environ, start_response )
File 'lib/galaxy/web/framework/base.py', line 193 in handle_request
  body = method( trans, **kwargs )
File 'lib/galaxy/webapps/galaxy/controllers/workflow.py', line 956 in import_workflow
  workflow, missing_tool_tups = self._workflow_from_dict( trans, data, source=src, add_to_menu=add_to_menu )
File 'lib/galaxy/web/base/controller.py', line 1180 in _workflow_from_dict
  exact_tools=exact_tools,
File 'lib/galaxy/managers/workflows.py', line 206 in build_workflow_from_dict
  exact_tools=exact_tools,
File 'lib/galaxy/managers/workflows.py', line 298 in _workflow_from_dict
  module, step = self.__track_module_from_dict( trans, steps, steps_by_external_id, step_dict, exact_tools=exact_tools )
File 'lib/galaxy/managers/workflows.py', line 850 in __track_module_from_dict
  module, step = self.__module_from_dict( trans, step_dict, exact_tools=exact_tools )
File 'lib/galaxy/managers/workflows.py', line 897 in __module_from_dict
  module.save_to_step( step )
File 'lib/galaxy/workflow/modules.py', line 880 in save_to_step
  step.tool_inputs = self.tool.params_to_strings( self.state.inputs, self.trans.app )
File 'lib/galaxy/tools/__init__.py', line 1372 in params_to_strings
  return params_to_strings( self.inputs, params, app )
File 'lib/galaxy/tools/parameters/__init__.py', line 149 in params_to_strings
  value = params[ key ].value_to_basic( value, app )
File 'lib/galaxy/tools/parameters/grouping.py', line 159 in value_to_basic
  rval[ input.name ] = input.value_to_basic( value[input.name], app )
KeyError: 'max_diff_mode'

```

**Comment by s-will** [comment]
great you could fix this! thanks a lot

**Comment by bgruening** [comment]
Sure! A few workflows would be neat, but you already did so much ...
I also checked rnaz, it works with the latest container. I guess It just was not up to date with your latest fixes.

**Comment by bgruening** [comment]
@s-will can you please pull the latest version, it should have your wf included but it uses outdated tools. Could you please check the parameters and update the infernal tool. Just save, export and update the yml on github. Than everything should be up to date. Thanks!

**Pull request merged**
