### PR TITLE
Galaxy-Workflow-trimming_mapping

### PR DESCRIPTION
**Pull request by dyusuf**
this workflow worked fine on the Freiburg instance. I am not sure if the memory issue (related to tophat) of the workbench has been resolved or not. If so, this workflow should work on the workbench.

### CODE REVIEW

**Comment by bgruening** [comment]
You need to add it here too: https://github.com/bgruening/galaxy-rna-workbench/blob/master/import_workflows.py#L10

**Comment by bgruening** [comment]
i haven't resolved the memory issue yet. Can you test it locally, with a local build? Or can anyone else help with this and look at the memory usage?

**Comment by dyusuf** [comment]
yes, I am doing so, just not sure the what absolute path needed here

**Comment by bgruening** [comment]
@dyusuf depends on where you store it with this statement: https://github.com/bgruening/galaxy-rna-workbench/blob/master/Dockerfile#L25

So you need to add it to the Container, and than "install" it.

Thanks a lot!

**Comment by bgruening** [comment]
ping @dyusuf!

**Comment by dyusuf** [comment]
ping @bgruening I don't understand the error.

**Comment by bgruening** [comment]
Can you give me the error I have only my mobile :-)

**Comment by dyusuf** [comment]
@bgruening 

test_run_cat1 (TestGalaxyTools.TestGalaxyTools) ... ok
test_run_random_lines (TestGalaxyTools.TestGalaxyTools) ... ok
test_upload_file (TestGalaxyTools.TestGalaxyTools) ... 

The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by bgruening** [comment]
Travis has a limit of 45min. Can you just rerun the tests?

**Pull request merged**
