### PR TITLE
Landing page creation

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I created a landing page for this project and a simple logo
When this PR will be merged, it will be available at: http://bgruening.github.io/galaxy-rna-workbench/

I am working on the welcome page now for Galaxy

Bérénice

### CODE REVIEW

**Comment by dyusuf** [comment]
the travis testing may fail because of the space limitation, see here #18

**Comment by bgruening** [comment]
This does not use submodules, correct? Is this intended?

**Comment by bebatut** [comment]
No submodule needed :)

**Comment by bgruening** [comment]
fontawesome?

**Comment by bebatut** [comment]
Directly the css file

**Comment by bebatut** [comment]
I do not use them. We can remove them, btw

**Comment by bgruening** [comment]
@dyusuf @jfallmann @s-will look at this: http://bgruening.github.io/galaxy-rna-workbench

**Comment by dyusuf** [comment]
@bebatut @bgruening the page looks great, especially the image!

wondering if should categorize the tools as I did in README.

**Pull request merged**
